import {FaHtml5, FaCss3, FaReact} from 'react-icons/fa'
import {SiNextdotjs, SiYoutube, SiMysql, SiJavascript, SiTailwindcss, SiFirebase, SiReact} from 'react-icons/si'
const portfolioData = [
  {
    id: 0,
    text: 'Website for churches, having a basic login and logout. Mostly displaying informations.',
    logoOne: <SiJavascript/>,
    logoTwo: <FaCss3/>,
    logoThree: <FaHtml5/>,
    logoFour: <SiTailwindcss/>,
    logoFive: <SiMysql/>,
    cn: 'w-80 h-80 object-cover drop-shadow-2xl',
    colorOne: 'text-[#EBB943]',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    colorFive: 'text-blue-300',
    img: '/pic1.png',
    link: 'https://www.netflix.com/',
},
{
    id: 1,
    text: 'Website for a client in West Africa. The website is also static, the client liked, the website the way it is.',
    logoOne: <SiJavascript/>,
    logoTwo: <FaCss3/>,
    logoFour: <SiTailwindcss/>,
    logoThree: <FaHtml5/>,
    cn: 'w-80 h-80 object-cover drop-shadow-2xl',
    colorOne: 'text-[#EBB943]',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    img: '/portfolioSMC.png',
    link: 'https://www.google.com/',
  },
{
    id: 2,
    text: 'I use fetch api from RapidApi and Pexels api to search for images, you can also remove background images all in one place. You can also download any image.',
    logoOne: <SiJavascript/>,
    logoTwo: <FaCss3/>,
    logoFour: <SiTailwindcss/>,
    logoThree: <FaHtml5/>,
    cn: 'w-80 h-80 object-cover  drop-shadow-2xl',
    colorOne: 'text-[#EBB943]',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    img: '/pic2.png',
    link: 'https://removebackground.netlify.app/',
  },
// {
//     id: 3,
//     text: 'Website for a client in West Africa. The website is also static, the client liked, the website the way it is.',
//     logoOne: <SiJavascript/>,
//     logoTwo: <FaCss3/>,
//     logoFour: <SiTailwindcss/>,
//     logoThree: <FaHtml5/>,
//     cn: 'row-span-2 sm:row-span-1 lg:h-80 h-full w-full xl:w-80 sm:h-40 object-cover object-center drop-shadow-2xl',
//     colorOne: 'text-[#EBB943]',
//     colorTwo: 'text-blue-500',
//     colorThree: 'text-orange-500',
//     colorFour: 'text-green-200',
//     img: '/code.jpg',
//     link: 'https://www.netflix.com/',
//   },
// {
//     id: 4,
//     text: 'Website for a client in West Africa. The website is also static, the client liked, the website the way it is.',
//     logoOne: <SiJavascript/>,
//     logoTwo: <FaCss3/>,
//     logoFour: <SiTailwindcss/>,
//     logoThree: <FaHtml5/>,
//     cn: 'w-full h-60 sm:h-40 object-cover lg:h-80 object-center xl:w-80 drop-shadow-2xl',
//     colorOne: 'text-[#EBB943]',
//     colorTwo: 'text-blue-500',
//     colorThree: 'text-orange-500',
//     colorFour: 'text-green-200',
//     img: '/pic3.jpg',
//     link: 'https://www.netflix.com/',
//   },
// {
//     id: 5,
//     text: 'Website for a client in West Africa. The website is also static, the client liked, the website the way it is.',
//     logoOne: <SiJavascript/>,
//     logoTwo: <FaCss3/>,
//     logoFour: <SiTailwindcss/>,
//     logoThree: <FaHtml5/>,
//     cn: 'col-span-2 sm:col-span-1 lg:h-80 w-full h-40 xl:w-80 object-cover object-center drop-shadow-2xl',
//     colorOne: 'text-[#EBB943]',
//     colorTwo: 'text-blue-500',
//     colorThree: 'text-orange-500',
//     colorFour: 'text-green-200',
//     img: '/pic2.jpg',
//     link: 'https://www.netflix.com/',
//   },

 
]

export default portfolioData;