import {FaHtml5, FaCss3, FaReact} from 'react-icons/fa'
import {SiNextdotjs, SiYoutube, SiMysql, SiJavascript, SiTailwindcss, SiFirebase, SiReact} from 'react-icons/si'
const portfolioData = [
  {
    id: 0,
    text: 'Website for churches, having a basic login and logout. Mostly displaying informations.',
    logoOne: <SiJavascript/>,
    logoTwo: <FaCss3/>,
    logoThree: <FaHtml5/>,
    logoFour: <SiTailwindcss/>,
    logoFive: <SiMysql/>,
    cn: 'w-80 h-80 object-cover drop-shadow-2xl',
    colorOne: 'text-[#EBB943]',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    colorFive: 'text-blue-300',
    img: '/pic1.png',
    link: '#',
},
{
    id: 1,
    text: 'Website for a client in West Africa. The website is also static, the client liked, the website the way it is.',
    logoOne: <SiJavascript/>,
    logoTwo: <FaCss3/>,
    logoFour: <SiTailwindcss/>,
    logoThree: <FaHtml5/>,
    cn: 'w-80 h-80 object-cover drop-shadow-2xl',
    colorOne: 'text-[#EBB943]',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    img: '/portfolioSMC.png',
    link: '#',
  },
{
    id: 2,
    text: 'I use fetch api from RapidApi and Pexels api to search for images, you can also remove background images all in one place. You can also download any image.',
    logoOne: <SiJavascript/>,
    logoTwo: <FaCss3/>,
    logoFour: <SiTailwindcss/>,
    logoThree: <FaHtml5/>,
    cn: 'w-80 h-80 object-cover  drop-shadow-2xl',
    colorOne: 'text-[#EBB943]',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    img: '/pic2.png',
    link: 'https://removebackground.netlify.app/',
  },
{
    id: 3,
    text: 'I built this real estate website that lets you search for location and will render the properties, you can also filter by any options you see there.',
    logoOne: <SiNextdotjs/>,
    logoTwo: <FaCss3/>,
    logoFour: <SiTailwindcss/>,
    logoThree: <FaHtml5/>,
    cn: 'w-80 h-80 object-cover  drop-shadow-2xl',
    colorOne: 'text-white',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    img: '/realestate1.png',
    link: 'https://winrealtor.netlify.app/',
  },
{
    id: 3,
    text: 'This is a fun personal project that I did to prepare to teach on youtube. It fetches api from pexels and has some cool 3D effect.',
    logoOne: <FaReact/>,
    logoTwo: <FaCss3/>,
    logoFour: <SiTailwindcss/>,
    logoThree: <FaHtml5/>,
    cn: 'w-80 h-80 object-cover  drop-shadow-2xl',
    colorOne: 'text-[#EBB943]',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    img: '/diamond.png',
    link: 'https://diamondxplore.netlify.app/',
  },
{
    id: 4,
    text: 'Website for a client in West Africa. The website is also static, the client liked, the website the way it is.',
    logoOne: <FaReact/>,
    logoTwo: <FaCss3/>,
    logoFour: <SiTailwindcss/>,
    logoThree: <FaHtml5/>,
    cn: 'w-80 h-80 object-cover  drop-shadow-2xl',
    colorOne: 'text-[#EBB943]',
    colorTwo: 'text-blue-500',
    colorThree: 'text-orange-500',
    colorFour: 'text-green-200',
    img: '/foodapp.mov',
    link: 'https://www.netflix.com/',
  },
// {
//     id: 5,
//     text: 'Website for a client in West Africa. The website is also static, the client liked, the website the way it is.',
//     logoOne: <SiJavascript/>,
//     logoTwo: <FaCss3/>,
//     logoFour: <SiTailwindcss/>,
//     logoThree: <FaHtml5/>,
//     cn: 'col-span-2 sm:col-span-1 lg:h-80 w-full h-40 xl:w-80 object-cover object-center drop-shadow-2xl',
//     colorOne: 'text-[#EBB943]',
//     colorTwo: 'text-blue-500',
//     colorThree: 'text-orange-500',
//     colorFour: 'text-green-200',
//     img: '/pic2.jpg',
//     link: 'https://www.netflix.com/',
//   },

 
]

export default portfolioData;